# Generated by Django 2.0.1 on 2018-02-01 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0002_auto_20180201_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
