# Generated by Django 2.0.1 on 2018-02-01 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0004_auto_20180201_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='reason',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
