# Generated by Django 2.0.1 on 2018-02-01 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0005_option_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='reason',
        ),
        migrations.AddField(
            model_name='page',
            name='reason',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
